[aliases]
gs = "git status"
ga = "git add"
gc = "git commit -m"
gp = "git push"
projects = "cd ~/projects"
configs = "cd ~/configs-files"

[functions.knd]
description = "Switch kubectl namespace"
commands = [
    "if ! kubectl config current-context >/dev/null 2>&1; then echo 'No kubectl context set. Run: kubectl config use-context <context>'; return 1; fi",
    "kubectl config set-context --current --namespace={arg}"
]
args = ["namespace"]

[functions.dam-update]
description = "Update system packages"
commands = [
    "brew bundle --file ~/configs-files/brew/Brewfile",
    "rustup update"
]

[functions.nx-run]
description = "Run Nx command on all projects"
command = "bun nx run-many -t {arg} --parallel --max-parallel=10 --prod"
args = ["task"]

[functions.kc]
description = "Create Kubernetes cluster"
type = "complex"
script = "~/configs-files/scripts/kc-cluster.nu"

[functions.build]
description = "Build nx monorepo project"
type = "complex"
script = "~/configs-files/scripts/nx.nu"

[environment]
EDITOR = "zed"
BROWSER = "open"