apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: XCluster
    plural: xclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "Cluster name"
              environment:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["local", "aks", "eks", "gke"]
                    description: "Cluster type"
                  region:
                    type: string
                    description: "Cloud region"
                  nodeCount:
                    type: integer
                    minimum: 1
                    maximum: 10
                    default: 3
                  nodeSize:
                    type: string
                    enum: ["small", "medium", "large"]
                    default: "medium"
                required:
                - type
              applications:
                type: object
                properties:
                  crossplane:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                  argocd:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                  prometheus:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                  loki:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
              cost:
                type: object
                properties:
                  budget:
                    type: integer
                    minimum: 0
                  alertThreshold:
                    type: integer
                    minimum: 0
                    maximum: 100
                    default: 80
            required:
            - name
            - environment
          status:
            type: object
            properties:
              ready:
                type: boolean
              uptime:
                type: string
              cost:
                type: object
                properties:
                  current:
                    type: number
                  projected:
                    type: number
  claimNames:
    kind: Cluster
    plural: clusters